export const FETCH_ALL_ARTICLES_REQUEST = 'FETCH_ALL_ARTICLES_REQUEST';
export const FETCH_ALL_ARTICLES_SUCCESS = 'FETCH_ALL_ARTICLES_SUCCESS';
export const FETCH_ALL_ARTICLES_FAILURE = 'FETCH_ALL_ARTICLES_FAILURE';

export const FETCH_ARTICLE_REQUEST = 'FETCH_ARTICLE_REQUEST';
export const FETCH_ARTICLE_SUCCESS = 'FETCH_ARTICLE_SUCCESS';
export const FETCH_ARTICLE_FAILURE = 'FETCH_ARTICLE_FAILURE';

export const UPDATE_ARTICLE_REQUEST = 'UPDATE_ARTICLE_REQUEST';
export const UPDATE_ARTICLE_SUCCESS = 'UPDATE_ARTICLE_SUCCESS';
export const UPDATE_ARTICLE_FAILURE = 'UPDATE_ARTICLE_FAILURE';

export const GET_ARTICLE_COMMENTS_REQUEST = 'GET_ARTICLE_COMMENTS_REQUEST';
export const GET_ARTICLE_COMMENTS_SUCCESS = 'GET_ARTICLE_COMMENTS_SUCCESS';
export const GET_ARTICLE_COMMENTS_FAILURE = 'GET_ARTICLE_COMMENTS_FAILURE';

export const ADD_COMMENT_REQUEST = 'ADD_COMMENT_REQUEST';
export const ADD_COMMENT_SUCCESS = 'ADD_COMMENT_SUCCESS';
export const ADD_COMMENT_FAILURE = 'ADD_COMMENT_FAILURE';

export const CLEAR_ARTICLE_ERROR = 'CLEAR_ARTICLE_ERROR';
export const CLEAR_COMMENT_ERROR = 'CLEAR_COMMENT_ERROR';
