export const FETCH_ALL_ARTICLES_REQUEST = 'FETCH_ALL_ARTICLES_REQUEST';
export const FETCH_ALL_ARTICLES_SUCCESS = 'FETCH_ALL_ARTICLES_SUCCESS';
export const FETCH_ALL_ARTICLES_FAILURE = 'FETCH_ALL_ARTICLES_FAILURE';

export const FETCH_ARTICLE_REQUEST = 'FETCH_ALL_ARTICLE_REQUEST';
export const FETCH_ARTICLE_SUCCESS = 'FETCH_ALL_ARTICLE_SUCCESS';
export const FETCH_ARTICLE_FAILURE = 'FETCH_ALL_ARTICLE_FAILURE';

export const GET_ARTICLE_COMMENTS_REQUEST = 'GET_ARTICLE_COMMENTS_REQUEST';
export const GET_ARTICLE_COMMENTS_SUCCESS = 'GET_ARTICLE_COMMENTS_SUCCESS';
export const GET_ARTICLE_COMMENTS_FAILURE = 'GET_ARTICLE_COMMENTS_FAILURE';
